/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/blog-editor`; params?: Router.UnknownInputParams; } | { pathname: `/message-detail`; params?: Router.UnknownInputParams; } | { pathname: `/user-detail`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}${'/(home)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/content` | `/content`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/more` | `/more`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/more/messages` | `/more/messages`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/more/notifications` | `/more/notifications`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/more/safety` | `/more/safety`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/more/sessions` | `/more/sessions`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/users` | `/users`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/blog-editor`; params?: Router.UnknownOutputParams; } | { pathname: `/message-detail`; params?: Router.UnknownOutputParams; } | { pathname: `/user-detail`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}${'/(home)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/content` | `/content`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/more` | `/more`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/more/messages` | `/more/messages`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/more/notifications` | `/more/notifications`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/more/safety` | `/more/safety`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/more/sessions` | `/more/sessions`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/users` | `/users`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/blog-editor${`?${string}` | `#${string}` | ''}` | `/message-detail${`?${string}` | `#${string}` | ''}` | `/user-detail${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/login${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${'/(home)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/content${`?${string}` | `#${string}` | ''}` | `/content${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/more${`?${string}` | `#${string}` | ''}` | `/more${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/more/messages${`?${string}` | `#${string}` | ''}` | `/more/messages${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/more/notifications${`?${string}` | `#${string}` | ''}` | `/more/notifications${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/more/safety${`?${string}` | `#${string}` | ''}` | `/more/safety${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/more/sessions${`?${string}` | `#${string}` | ''}` | `/more/sessions${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/users${`?${string}` | `#${string}` | ''}` | `/users${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/blog-editor`; params?: Router.UnknownInputParams; } | { pathname: `/message-detail`; params?: Router.UnknownInputParams; } | { pathname: `/user-detail`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}${'/(home)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/content` | `/content`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/more` | `/more`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/more/messages` | `/more/messages`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/more/notifications` | `/more/notifications`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/more/safety` | `/more/safety`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/more/sessions` | `/more/sessions`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/users` | `/users`; params?: Router.UnknownInputParams; } | `/+not-found${`?${string}` | `#${string}` | ''}` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
